name: Publish NuGet Package

on: push

env:
  MAIN_VER: 1

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd TestNuGet
          dotnet pack --configuration Release
          dotnet nuget push "bin/Release/TestNuGet.1.0.0.nupkg" --source "github"
