name: Publish NuGet Package

on: push

env:
  MAIN_VER: 1

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to GitHub Packages
        run: |
          cd TestNuGet
          dotnet pack --configuration Release
